const appName = "MyShop";
const latoFont = "Lato";
const onlyFavorites = "Only Favorites";
const showAll = "Show All";
const emptyFavMsg = "No favorites to show. Add some!";
const yourCart = "Your Cart";
const total = "Total";
const orderNow = 'ORDER NOW';
const yourOrders = 'Your Orders';
const orders = 'Orders';
const shop = 'Shop';
const drawerTitle = "Hello Friend!";
const cartAddedMsg = 'Added item to cart!';
const undo = 'UNDO';
const dismissDialogTitleText = 'Are you sure?';
const dismissDialogContentText =
    "Do you want to remove the item from the cart?";
const yes = "Yes";
const no = "No";
const yourProducts = 'Your Products';
const manageProducts = 'Manage Products';
const editProduct = "Edit Products";
const title = 'Title';
const price = 'Price';
const description = 'Description';
const imageUrl = "Image URL";
const enterImageUrl = "Enter a URL";
const baseUrl =
    "flutter-shop-app-e2f5f-default-rtdb.asia-southeast1.firebasedatabase.app";